### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by michaelDotco2** [melat0nin/concrete5_ajax_page_list#2]
doesn't work

**Comment by melat0nin** [comment]
...can you be more specific?

**Comment by michaelDotco2** [comment]
Actually it does but just not with cleaner URLS 
eg. define('PAGING_STRING', 'page'); outlined here,
http://concrete5tricks.com/blog/pagination-with-the-page-list-class/
I have just removed this and it is working.
Thanks.

**Comment by melat0nin** [comment]
Thanks for pointing this out. I don't imagine many people are using that configuration option (plus there's no need for it with this AJAX page list since users never see the URLs), so I'll close this issue.
